### ISSUE TITLE
Battle Tower: Skillpoints not controllable

### ISSUE THREAD

**Issue by Hughdeenee** [eyewars/Energy-Generator#1]
Clicking the "+" sign next to the stats adds all available skillpoints to that stat, clicking the "-" sets it to zero.

Expected behavior:
Clicking "+" and "-" increases respectively decreases the stat value by 1.

I don't see a way to in/decrease the value by anything other than everything, whicht is utterly useless. Please provide a way to control the distribution of skillpoints.

**Comment by eyewars** [comment]
Tap shift, ctrl or alt to fix it. The problem is that when you hold one of those buttons (in your case alt), and you then tab out or click on another window, the game doesn't realise that you stopped holding the button. If you click on any of them then the game will see that you're now holding that butten and when you release it it's back to normal.

**Comment by Hughdeenee** [comment]
Thanks for the info. Alt+Tab, Ctrl+Tab and the like are pretty much to be expected. If you can't solve the issue, I suggest you display the current mode along with the information on how to change it. I'm probably not the only one experiencing this weird behaviour, and most people won't search for a repository ;)
(And btw, thanks for the awesome game!)

**Comment by eyewars** [comment]
Yeah I'll probably add a little note in the info tab :P

(ty :D)
